/**
 * Builds the SQL that loads the test salon (lib/fixtures.ts) into the database.
 * Used by scripts/seed.ts and by tests/db.test.ts.
 *
 * Safe to run again: it updates the salon row in place and replaces all of its
 * staff, services, customers and bookings. Users linked in salon_users stay.
 */
import { buildFixtures, FIXTURE_SALON_ID } from "../lib/fixtures";

type Row = Record<string, unknown>;

const ROWS_PER_INSERT = 200;

function literal(value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new Error(`Not a finite number: ${value}`);
    return String(value);
  }
  if (typeof value === "string") return `'${value.replaceAll("'", "''")}'`;
  throw new Error(`Unsupported value in seed data: ${typeof value}`);
}

/** Every column of the rows, except generated ones the database computes itself. */
function columnsOf(rows: Row[], skip: string[] = []): string[] {
  return rows.length ? Object.keys(rows[0]).filter((c) => !skip.includes(c)) : [];
}

function insert(table: string, rows: Row[], skip: string[] = []): string {
  if (rows.length === 0) return "";
  const columns = columnsOf(rows, skip);
  const statements: string[] = [];
  for (let i = 0; i < rows.length; i += ROWS_PER_INSERT) {
    const values = rows
      .slice(i, i + ROWS_PER_INSERT)
      .map((row) => `  (${columns.map((c) => literal(row[c])).join(", ")})`)
      .join(",\n");
    statements.push(`insert into ${table} (${columns.join(", ")}) values\n${values};`);
  }
  return statements.join("\n\n");
}

export function buildSeedSql(now: Date): string {
  const f = buildFixtures(now);
  const salon = f.salons[0] as unknown as Row;
  const salonColumns = columnsOf([salon]);
  const id = literal(FIXTURE_SALON_ID);

  const upsertSalon =
    `insert into salons (${salonColumns.join(", ")}) values\n` +
    `  (${salonColumns.map((c) => literal(salon[c])).join(", ")})\n` +
    `on conflict (id) do update set\n` +
    salonColumns
      .filter((c) => c !== "id")
      .map((c) => `  ${c} = excluded.${c}`)
      .join(",\n") +
    ";";

  return [
    `-- Test salon "Frizerstvo Test" (slug "test"): generated by \`npm run seed\``,
    `-- on ${now.toISOString()} from lib/fixtures.ts. Do not edit; run the command again.`,
    `-- Fake data only. Dates are relative to the moment it was generated.`,
    `-- Running it again resets the test salon's data; salon_users rows stay.`,
    "",
    "begin;",
    "",
    "-- Remove the previous test data (children before parents).",
    `delete from bookings where salon_id = ${id};`,
    `delete from payments where salon_id = ${id};`,
    `delete from customers where salon_id = ${id};`,
    `delete from time_off where salon_id = ${id};`,
    `delete from staff_hours where salon_id = ${id};`,
    `delete from staff_services where salon_id = ${id};`,
    `delete from services where salon_id = ${id};`,
    `delete from staff where salon_id = ${id};`,
    "",
    upsertSalon,
    "",
    insert("staff", f.staff as unknown as Row[]),
    "",
    insert("services", f.services as unknown as Row[]),
    "",
    insert("staff_services", f.staffServices as unknown as Row[]),
    "",
    insert("staff_hours", f.staffHours as unknown as Row[]),
    "",
    insert("time_off", f.timeOff as unknown as Row[]),
    "",
    insert("customers", f.customers as unknown as Row[]),
    "",
    "-- period is a generated column, the database computes it.",
    insert("bookings", f.bookings as unknown as Row[], ["period"]),
    "",
    "commit;",
    "",
  ].join("\n");
}
